DROP TABLE CONTRACT IF EXISTS;

CREATE TABLE CONTRACT (
    contractId BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL,
    contractCode VARCHAR(100) NOT NULL,
    contractDescription VARCHAR(200),
    startDate DATETIME,
    endDate DATETIME,
    vendor VARCHAR(200),
    projectId BIGINT,
    percentComplete DOUBLE DEFAULT 0.0,
    contractStatus VARCHAR(15),
    budget NUMERIC(19,2) DEFAULT 0.0,
    payment NUMERIC(19,2) DEFAULT 0.0,
    forecast NUMERIC(19,2) DEFAULT 0.0,
    committed NUMERIC(19,2) DEFAULT 0.0,
    status VARCHAR(15),
    PRIMARY KEY (contractId)
);